### PR TITLE
Open external YT comment link in new tab, fix timestamp parsing, remove duplicate timestamps

### LINKED ISSUE #47: Opening Youtube comment source doesn't open in new tab
For consistency and usability, the comment's source link should open in a new tab just like the "Open on YouTube" button does under the video for Watch pages.

### PR DESCRIPTION
**Pull request by michaelnguyenm**
Added the target and rel attributes for the external YouTube comment link so the link should open in a new tab by default.

### CODE REVIEW

File: src/components/watch/WatchComments.vue [hunk 1]
```diff
@@ -82,20 +82,20 @@ export default {
...
                 while (match != null) {
                     const hr = match[1];
                     const min = match[2];
                     const sec = match[3];
                     const time = Number(hr ?? 0) * 3600 + Number(min) * 60 + Number(sec);
-                    times.push(time);
+                    times.add(time);
                     match = COMMENT_TIMESTAMP_REGEX.exec(c.message);
                 }
                 c.times = times;
```
Comment (RiceCakess) [inline src/components/watch/WatchComments.vue:101]: `c.times = Array.from(times)`, just convert before setting.  That way on line 85 doesn't need to convert for each filter operation.  Other than that, looks good to merge
